### ISSUE TITLE
后端启动问题

### ISSUE THREAD

**Issue by Roses-and-Gold** [fanchaoo/netease-cloud-music-community#5]
大佬你好，我发现后端启动有点问题，报错如下（我在网上搜的好像是注入依赖失败）我不知道具体怎么改呀： 
[tartedMain] letWebServerApplicationContext( 558) - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'collectController': Unsatisfied dependency expressed through field 'collectService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'collectServiceImpl': Unsatisfied dependency expressed through field 'momentService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'momentServiceImpl': Unsatisfied dependency expressed through field 'notificationService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'notificationServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.VerifyError: Stack map does not match the one at exception handler 9
下面是详细报错（看网上说是动态代理之类的问题，我也不懂。会不会是idea版本的问题？我的idea是社区版的）
Exception Details:
  Location:
    me/fanchaoo/web/service/impl/MomentServiceImpl$$EnhancerBySpringCGLIB$$5a745fb7.<init>()V @9: athrow
  Reason:
    Current frame's flags are not assignable to stack map frame's.
  Current Frame:
    bci: @0
    flags: { flagThisUninit }
    locals: { uninitializedThis }
    stack: { 'java/lang/RuntimeException' }
  Stackmap Frame:
    bci: @9
    flags: { }
    locals: { }
    stack: { 'java/lang/Throwable' }
  Bytecode:
    0x0000000: 2a59 b701 9cb8 0038 b1bf bb00 4c5a 5fb7
    0x0000010: 004f bf                                
  Exception Handler Table:
    bci [0, 9] => handler: 9
    bci [0, 9] => handler: 9
    bci [0, 9] => handler: 10
  Stackmap Table:
    full_frame(@9,{},{Object[#74]})
    same_locals_1_stack_item_frame(@10,Object[#74])

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:571)

**Comment by fanchaoo** [comment]
JDK是1.8吗，再高的估计支持不了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanchaoo/netease-cloud-music-community"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月15日(星期二) 中午1:29
收件人:&nbsp;"fanchaoo/netease-cloud-music-community"<netease-cloud-music-community@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[fanchaoo/netease-cloud-music-community] 后端启动问题 (#5)





 
大佬你好，我发现后端启动有点问题，报错如下（我在网上搜的好像是注入依赖失败）我不知道具体怎么改呀：
 [tartedMain] letWebServerApplicationContext( 558) - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'collectController': Unsatisfied dependency expressed through field 'collectService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'collectServiceImpl': Unsatisfied dependency expressed through field 'momentService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'momentServiceImpl': Unsatisfied dependency expressed through field 'notificationService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'notificationServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.VerifyError: Stack map does not match the one at exception handler 9
 下面是详细报错（看网上说是动态代理之类的问题，我也不懂。会不会是idea版本的问题？我的idea是社区版的）
 Exception Details:
 Location:
 me/fanchaoo/web/service/impl/MomentServiceImpl$$EnhancerBySpringCGLIB$$5a745fb7.()V @9: athrow
 Reason:
 Current frame's flags are not assignable to stack map frame's.
 Current Frame:
 bci: @0
 flags: { flagThisUninit }
 locals: { uninitializedThis }
 stack: { 'java/lang/RuntimeException' }
 Stackmap Frame:
 bci: @9
 flags: { }
 locals: { }
 stack: { 'java/lang/Throwable' }
 Bytecode:
 0x0000000: 2a59 b701 9cb8 0038 b1bf bb00 4c5a 5fb7
 0x0000010: 004f bf
 Exception Handler Table:
 bci [0, 9] =&gt; handler: 9
 bci [0, 9] =&gt; handler: 9
 bci [0, 9] =&gt; handler: 10
 Stackmap Table:
 full_frame(@9,{},{Object[#74]})
 same_locals_1_stack_item_frame(@10,Object[#74])
 at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Class.java:348) at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:571)

**Comment by Roses-and-Gold** [comment]
> JDK是1.8吗，再高的估计支持不了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "fanchaoo/netease-cloud-music-community" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月15日(星期二) 中午1:29 收件人:&nbsp;"fanchaoo/netease-cloud-music-community"<netease-cloud-music-community@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[fanchaoo/netease-cloud-music-community] 后端启动问题 (#5) 大佬你好，我发现后端启动有点问题，报错如下（我在网上搜的好像是注入依赖失败）我不知道具体怎么改呀： [tartedMain] letWebServerApplicationContext( 558) - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'collectController': Unsatisfied dependency expressed through field 'collectService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'collectServiceImpl': Unsatisfied dependency expressed through field 'momentService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'momentServiceImpl': Unsatisfied dependency expressed through field 'notificationService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'notificationServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.VerifyError: Stack map does not match the one at exception handler 9 下面是详细报错（看网上说是动态代理之类的问题，我也不懂。会不会是idea版本的问题？我的idea是社区版的） Exception Details: Location: me/fanchaoo/web/service/impl/MomentServiceImpl$$EnhancerBySpringCGLIB$$5a745fb7.()V @9: athrow Reason: Current frame's flags are not assignable to stack map frame's. Current Frame: bci: @0 flags: { flagThisUninit } locals: { uninitializedThis } stack: { 'java/lang/RuntimeException' } Stackmap Frame: bci: @9 flags: { } locals: { } stack: { 'java/lang/Throwable' } Bytecode: 0x0000000: 2a59 b701 9cb8 0038 b1bf bb00 4c5a 5fb7 0x0000010: 004f bf Exception Handler Table: bci [0, 9] =&gt; handler: 9 bci [0, 9] =&gt; handler: 9 bci [0, 9] =&gt; handler: 10 Stackmap Table: full_frame(@9,{},{Object[#74]}) same_locals_1_stack_item_frame(@10,Object[#74]) at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Class.java:348) at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:571) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是1.8呀

**Comment by fanchaoo** [comment]
这就不太清楚了，可以再搜搜看





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanchaoo/netease-cloud-music-community"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月15日(星期二) 中午1:54
收件人:&nbsp;"fanchaoo/netease-cloud-music-community"<netease-cloud-music-community@noreply.github.com&gt;;
抄送:&nbsp;"范超"<1104641801@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [fanchaoo/netease-cloud-music-community] 后端启动问题 (#5)





  
JDK是1.8吗，再高的估计支持不了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "fanchaoo/netease-cloud-music-community" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月15日(星期二) 中午1:29 收件人:&nbsp;"fanchaoo/netease-cloud-music-community"<netease-cloud-music-community@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[fanchaoo/netease-cloud-music-community] 后端启动问题 (#5) 大佬你好，我发现后端启动有点问题，报错如下（我在网上搜的好像是注入依赖失败）我不知道具体怎么改呀： [tartedMain] letWebServerApplicationContext( 558) - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'collectController': Unsatisfied dependency expressed through field 'collectService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'collectServiceImpl': Unsatisfied dependency expressed through field 'momentService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'momentServiceImpl': Unsatisfied dependency expressed through field 'notificationService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'notificationServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.VerifyError: Stack map does not match the one at exception handler 9 下面是详细报错（看网上说是动态代理之类的问题，我也不懂。会不会是idea版本的问题？我的idea是社区版的） Exception Details: Location: me/fanchaoo/web/service/impl/MomentServiceImpl$$EnhancerBySpringCGLIB$$5a745fb7.()V @9: athrow Reason: Current frame's flags are not assignable to stack map frame's. Current Frame: bci: @0 flags: { flagThisUninit } locals: { uninitializedThis } stack: { 'java/lang/RuntimeException' } Stackmap Frame: bci: @9 flags: { } locals: { } stack: { 'java/lang/Throwable' } Bytecode: 0x0000000: 2a59 b701 9cb8 0038 b1bf bb00 4c5a 5fb7 0x0000010: 004f bf Exception Handler Table: bci [0, 9] =&gt; handler: 9 bci [0, 9] =&gt; handler: 9 bci [0, 9] =&gt; handler: 10 Stackmap Table: full_frame(@9,{},{Object[#74]}) same_locals_1_stack_item_frame(@10,Object[#74]) at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Class.java:348) at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:571) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
是1.8呀

**Comment by fanchaoo** [comment]
close
